all: t1 t2 t3 t4
	@echo "Building Target"	

t1: q1.cpp 
	@g++ -std=c++11 q1.cpp -o q1_result

t2: q2.cpp
	@g++ -std=c++11 q2.cpp -o q2_result

t3: q3.cpp
	@g++ -std=c++11 q3.cpp -o q3_result

t4: q4.cpp OrderedMap.h
	@g++ -std=c++11 q4.cpp -o q4_result




