target: t1 t2 t3 
	@echo "Building Target"	

t1: q1.cpp Sort.h
	@g++ -std=c++11 q1.cpp -o q1_result

t2: q2_1.cpp MinHeap.h
	@g++ -std=c++11 q2_1.cpp -o q2_1_result

t3: q2_3.cpp MinHeap.h
	@g++ -std=c++11 q2_3.cpp -o q2_3_result

all: target


